### ISSUE TITLE
Could the option of returning raw Json be added to the client ?

### ISSUE THREAD

**Issue by peterkd** [fuzzzerd/fmdata#29]
Instead of parsing the json to iDictionary, it would be very handy to get the raw json in addition to the dictionary

**Comment by fuzzzerd** [comment]
What would be the advantage of the library if it just returns the raw JSON? At that point you might be better served by calling the Data API directly with an HttpClient.

I'd be curious what you think an API that returns the raw JSON might look like and how it'd be used.

**Comment by peterkd** [comment]
Hi Nate,

The value of the library to me is all the wrappers for FM API - for all the FM calls such as find. I like the one liner client and how I can specify details for the requests.

For my purpose I need raw Json that I pass on to data factory for further transformation, so I serialize the result from IDictionary back to Json... this is causing some issues on my end, so the raw call would be super helpful.

Any chance to include it relatively soon? I may need to revert to Http client without raw Json...

Thanks,

Peter

**Comment by peterkd** [comment]
The authentication logic is also a major benefit.

**Comment by fuzzzerd** [comment]
In order to do this properly would require some refactoring of the internals of the library. I'm currently working towards getting v2.1 released. I'm slating this for v2.2 for now, at least and until its determined if it will be a breaking change or not (then it'd probably go for v3).

**Comment by fuzzzerd** [comment]
I do not see a way to provide the raw json data without extending the surface area of the API significantly. Since our downstream API is not guaranteed to be the FileMaker Data API (could be xml, odbc, or whatever FMI cooks up next) I think this might make sense to be included in the `IFileMakerRestClient.` 

With that established, I think it makes sense to refactor the existing `SendAsync` methods to build the output JSON in a more unified way as well as process the responses in a more unified way. Once that foundational work is completed we can factor out the JSON handling and make that available via the public interface of `IFileMakerRestClient` without having a negative impact on the more general `IFileMakerApiClient.`

Given the scope of that rewrite, I'm going to pull this from v2.2, since everything else there is baked and ready to go out. This could potentially be a v2.3 thing or maybe a v3.0 thing.

**Comment by fuzzzerd** [comment]
@peterkd can you try out the latest MyGet build?

**Comment by fuzzzerd** [comment]
Based on the latest refactoring, I've come up with what I think is a reasonable compromise to get the raw data out. 

For a Create Record request, it might look something like this:

```csharp
var req = YourFunction(); // that returns ICreateRequest<T>
var requestUri = CreateEndpoint(req.Layout);
var responseMessage = await ExecuteRequestAsync(HttpMethod.Post, requestUri, req);
```

This provides the full raw `HttpResponseMessage` including statuses returned by FileMaker Server in addition to the raw response.

Consuming the result of this new method would go something like this at a basic level:

```csharp
var responseJson = await responseMessage.Content.ReadAsStringAsync();
```

The internals of the library (all of the existing `SendAsync<T>(...)` methods have been converted to use this new request processor, so there's several examples of usage there.
