### ISSUE TITLE
Add option to select the DataAPI version

### ISSUE THREAD

**Issue by MichaelL79** [fuzzzerd/fmdata#371]
It seems, that using **v1** in the DataAPI URI causes problems when used with FileMaker 21. I'm not enirely sure that v1 / v2 / vLatest ist really the cause of the issue but at least it seems to be. In any case it would be great to select the version to be used when creating a new FileMakerRestClient. Even if this is not the cause of our problems, at least we could rule it out this way.

**Comment by fuzzzerd** [comment]
This would be an interesting feature for the future. As it stands right now there seem to be [very few if any changes between `v1` and `v2` though official documentation is sparse.](https://community.claris.com/en/s/question/0D50H0000812A7PSAU/filemaker-19-data-api-changes)

If this is a feature you are interested in developing, I'd be glad to help guide you to getting a PR merged. Couple thoughts:

- Class level "TargetVersion" enum variable.
- Update the various Endpoint helper methods to use this variable to generate paths.
- Additional constructor overload to allow specifying a target version.

This approach would allow future features to be implemented (and eventually removed features to remain) by allowing the endpoint calculation to override the TargetVersion if the requested endpoint is less or greater than the target. Currently this isn't necessary but it allows for it into the future.

**Comment by fuzzzerd** [comment]
> I cloned the repository and implemented the changes and tests. Would be great if you guide me through the PR process.

That's great! Thank you. Generally, you'll want to Fork the repository, so that you can create a topic branch for the change, and then once you have committed that and synced it to your fork, you can submit a PR from your fork to this repository. Here's a couple GitHub links on these things:

- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Once you've got the PR created in this repository, I'll be glad to review and work with you to get ready to merge.

**Comment by fuzzzerd** [comment]
Implemented in #372.
